import phone

my_phone = phone.Phone('0549200199')
other_phone = phone.Phone('0549448588')


my_phone.call(other_phone)
my_phone.call(other_phone)
other_phone.call(my_phone)
my_phone.call(other_phone)
other_phone.call(my_phone)

print('---------------------------------------')
my_phone.show_call_history()
print('---------------------------------------')
other_phone.show_call_history()
print('---------------------------------------')
my_phone.send_message(other_phone, 'Hello.')
other_phone.send_message(my_phone, 'My name is Inigo montoya.')
my_phone.send_message(other_phone, 'You killed my father.')
other_phone.send_message(my_phone, 'Prepare to die.')
print('---------------------------------------')
print('-------------------show_incoming_messages--------------------')
my_phone.show_incoming_messages()
print('-------------------show_outgoing_messages--------------------')
my_phone.show_outgoing_messages()
print('-------------------show_messages_from--------------------')
my_phone.show_messages_from(other_phone)
print('-------------------show_incoming_messages--------------------')
print('---------------------------------------')
other_phone.show_incoming_messages()
print('-------------------show_outgoing_messages--------------------')
other_phone.show_outgoing_messages()
print('-------------------show_messages_from--------------------')
other_phone.show_messages_from(my_phone)
print('---------------------------------------')